- name: download nodejs from source
  unarchive:
    src: https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/node-v16.20.2-linux-x64

- name: symlink node to node
  file:
    src: /usr/local/node-v16.20.2-linux-x64/bin/node
    dest: /usr/local/bin/node
    state: link
    force: yes

- name: symlink npm to npm
  file:
    src: /usr/local/node-v16.20.2-linux-x64/bin/npm
    dest: /usr/local/bin/npm
    state: link
    force: yes
